serialize_client:
	g++ -o client tinyxml2.cpp serialize_client.cpp 

multi_client:
	g++ -o multi_client tinyxml2.cpp multi_client.cpp -lpthread

randomize_client:
	g++ -o randomize_client tinyxml2.cpp randomize_client.cpp -lpthread