version: '2'

services:
  app:
    build: 
      context: ./src
      dockerfile: Dockerfile
    command: bash -c "chmod o+x run.sh && ./run.sh"
    ports:
      - "12345:12345"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=trades

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=trades
    command: postgres -c 'max_connections=1000'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
